### ISSUE TITLE
[Benchmarks] Support the display of benchmarks through thresholds

### ISSUE THREAD

**Issue by Startrekzky** [merico-dev/table#1384]
## Goal
Show the benchmark icon on the top-right corner based on the configured thresholds
![image](https://github.com/merico-dev/table/assets/14050754/e45a8d0e-2154-45e1-996b-f3cf695622ba)

## Description
This requires users to 
1. define the thresholds for the metrics as below
![image](https://github.com/merico-dev/table/assets/14050754/dc3d42f3-a6e1-410f-bebe-a55b68244282)

   - For the first step, the absolute threshold is enough
   - In addition to the screenshot, allow users to choose the emoji for each threshold

   Please refer to Grafana's doc for more information: https://grafana.com/docs/grafana/latest/panels-visualizations/configure-thresholds/

2. Display the emoji at the top-right corner of a panel
   - Support it in the Cartesian Chart and Stats chart. For the Cartesian chart, the level depends on which threshold/bucket the avg number of metrics falls into.
   - Provide an option for users to decide whether to show the emoji on the panel.
   - When hovering on the emoji, show the full thresholds (i.e. benchmarks) in readable language.

**Comment by GerilLeto** [comment]
After discussion, actual requirements are these

**Variable**
- add Threshold aggregation

**Panel Description**
1. add Show Description checkbox
2. able to use panel variables in panel description
3. able to customize panel description's trigger icon
4. able to use current threshold range's icon as panel description's trigger icon

**Comment by Startrekzky** [comment]
I'll close the issue as there are disputes regarding the solutions. We'll implement a private component and see if it works out.
