### ISSUE TITLE
use queries as filter options

### ISSUE THREAD

**Issue by ZeekoZhu** [merico-dev/table#377]
- [ ] allow creating new queries from filter settings modal
- [ ] allow using existing queries as options of "select" filter

**Comment by GerilLeto** [comment]
it will cause circular dependency

- queries use sql snippets
- snippets use filters
- if filters use queries...

if there's a way to avoid this problem, letting filters use queries would be really nice

**Comment by ZeekoZhu** [comment]
![image](https://user-images.githubusercontent.com/13861843/202604899-813b86f0-a8e7-4b1e-bc69-1aeec4ab9703.png)

doesn't seem to cause a circular dependency, it uses current filter values instead of the filter options when evaluating query SQL, and in our code, the filter values have been decoupled from the FilterModel

**Comment by ZeekoZhu** [comment]
And the whole picture may look like this: [Diagram](https://viewer.diagrams.net/?tags=%7B%7D&highlight=0000ff&edit=_blank&layers=1&nav=1&title=Untitled%20Diagram.drawio#R7Vpdc9o6EP01PJaxpRjDYxKS3rmTzrRDp22eMgILrF5jubIIkF9fyZL8gYGYEiOnc5%2BwVivZ3j1nd7WmB2%2BXm48MJeEnGuCoB5xg04PjHgCuO%2FTEj5RslWQAoRIsGAm0UiGYkBeshY6WrkiA04oipzTiJKkKZzSO8YxXZIgxuq6qzWlUvWuCFrgmmMxQVJd%2BJwEPlXToOYX8H0wWobmz6%2BiZJTLKWpCGKKDrkgje9eAto5Srq%2BXmFkfSeMYuat39gdn8wRiOeZMF%2FLt3vYlG2%2BTfp%2BnTyKf3%2F6HHDy5Q2zyjaKXfWD8t3xoT4EBYRA8p4yFd0BhFd4X0htFVHGB5H0eMCp0HShMhdIXwJ%2BZ8q92LVpwKUciXkZ5NOWL8WrpLCGIaYyO7J1Gkt8VxYDQCgpY0Dr6GJFYTJTX1%2BPKZD9pJi1K6YjN8zDjac%2BJBFpgfU3RzfwoiYLrEnG3FQoYjxMlz9UmQRuQi1yucJi60307xoVPzobAHxyzVdNzxZ9Vb65BwPElQZom1IHHVM3przDjeHDdo%2FfX1AjDUD6hDwJUhz7oglGtYEpbINHDastjwf9S%2FAuYmqPetot6t%2BbDf74utngkWQR%2FcZ6OOQR%2B6tqGfZ6OLIh1vCP9Run6UW%2FU9PRpvDNjlYJsjX7zvj%2FKgtEoOi2XZyKyrsKrKmSPk0vRrj1V%2BU1aNrLLKr7FqjNJwShELuplNXN82peD7o5R7BqVeT1Q0wa1mKAgacgkMz%2BRStlS8FtqWFBJKYp6Wdv4sBQVCfbgT9OFOYf6K%2FtDZgaR6gAKg%2BZucgdk6z1cplsaPSZJgnh2zpL%2BkAuJy5tcKZ8abfHnYi%2FcHNBXhoYJRFJGFQMJ4JlyMmRBI5hNxuLrWE0sSBIoOOCUvaJrtJ9GibSw292563lhuSxl5oTFHVUDtiSX6KKh36%2BUHsDLUjhD5YOT54PQd7wpWfKWReBqgCgQYFTqfp9LoO5HoDRyt0smeMkm6k%2BCuFEreoGtRHXg2o3oRyR%2FLgfyVQqkI5I%2FlIP82Uf1Cxw%2FQ%2BPhxgK2XKZSA%2F%2B6SfrvwaDvpN8aFqg5s4QLW461KrCZ9Zml1jvksFL804YTGqbyaSyPgSPYwsxTGGa0X2xfIs2%2BfVsGBPkGRViE0XeHuJlJQ7zeoLls3j0XeyHoCHby%2FCNnqsehSCRS%2BjwQKD%2FDpmxSk1gnVuaY1GFktSE%2FgU0d5MWzKC6t9behadfMJ546uFYhN%2FasijzX%2FDg4UiPMs%2BuUz9QZM3pr5G4pCeDz6yqLQ9UAlBLudLxHrnxUnymcd%2BRK722WxntPglZVg91c1TBp3w%2B1%2BWYJ2%2B2l%2F1jDxK%2Fhw3hYfexPiz9UyMTZBbGYJKmenyD%2F6cOKB0z6c7OoD%2F7h%2B3lTer9%2FSl5Z6UmiY7y1%2FcGkh53tHs5PTv3LOTfKmG%2BKD6pL2kr7hVOW%2FRINI2OEmIM%2FiciEvv0hf6iJATU6ZmTMScfvSis4VC9Bpr1oQw%2BKPkMozxd9J4d1v)
