### ISSUE TITLE
The panel variable with aggregation none shows "Array(1)", but expect a number

### ISSUE THREAD

**Issue by liangjingyang** [merico-dev/table#672]
<img width="1532" alt="image" src="https://user-images.githubusercontent.com/2056705/220330559-27d50670-9abd-40d4-ba27-5855d8853f54.png">

I remember it's a number in the old version. The current version is 7.20.2. 

It becomes a number when I change the aggregation to SUM.

**Comment by GerilLeto** [comment]
since https://github.com/merico-dev/table/issues/653 , "None" aggregation no longer returns number :)

**Comment by GerilLeto** [comment]
viz-stats' initial config is not valid since #653 , reopening this issue to fix this

**Comment by GerilLeto** [comment]
viz-stats' initial config doesnt include variables, nothing to do here
