### ISSUE TITLE
Nothing to display after saving changes

### ISSUE THREAD

**Issue by liangjingyang** [merico-dev/table#814]
The web page has noting to show, becomes  a blank page, and there are some errors in console:

<img width="2551" alt="image" src="https://user-images.githubusercontent.com/2056705/229259522-9c1c54bc-539a-410a-8243-4d5ec85948f6.png">

I tried to refresh the page, but still blank page.

I tried to enter the dashboard from navigation, but failed:
<img width="2556" alt="image" src="https://user-images.githubusercontent.com/2056705/229259599-4e34c012-73b5-43dc-95fb-112ff2d8ebf3.png">

The dashboard ID: 4a22af7b-c885-4322-8b79-a04fd06d314a

**Comment by GerilLeto** [comment]
fifth panel has invalid layout value

`panel.layout.y` is supposed to be a number, but somehow it's `null`
